### ISSUE TITLE
Vendor Location Owner must be Farmer Code not Name

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#21]
Assigning the Name of a _Farmer_ for the _Vendor Location_ as _Owner_ is not secure because _Name_ is not unique. It would be better to use a unique field such as the _Farmer Code_.

**Comment by treviser** [comment]
@dastcaboz Please check on test-caboz and close if it works as expected.

**Comment by dastcaboz** [comment]
Still just the name displayed. It should be the farmer code instead. Name field is OK but just as view field after the Farmer Code was selected.
<img width="1440" alt="Bildschirmfoto 2021-09-30 um 12 20 21" src="https://user-images.githubusercontent.com/90847414/135438039-fe4c1203-9512-4f2a-bf66-b567a1861dec.png">

**Comment by candidroot** [comment]
@treviser 

Can we display owner field value like "[Farmer code] farmer name"
Example : "[CRS/1026] ASSIRI Yao Jules"

So here you can see farmer name as well as code 
Please let me know if is it fine or not ???

**Comment by treviser** [comment]
@candidroot 
This is a good idea. As we have more than 1500 farmers in the database, the forward typing feature (autocompletion) is essential. So if it is also possible with your suggestion to type for example "1026" or "Yao" in order to find the corresponding selection containing the same farmer, then it is ok from my point of view.

**Comment by candidroot** [comment]
@treviser 
Hello As per Comment i have update code you can search using code and name in owner field.
Please let me know is there any update on this,
thanks

**Comment by treviser** [comment]
@candidroot 
After a short test I see that I can use forward typing for the name, but not for the code. When I enter for example 1026, it asks me to create a new owner instead of showing me ASSIRI:

![image](https://user-images.githubusercontent.com/1814941/135815441-500cdf5c-3888-49ea-8b03-0f34de98f423.png)

**Comment by candidroot** [comment]
@treviser 
I already commit code please take latest pull and upgrade module then please check it
thanks.

**Comment by dastcaboz** [comment]
Is there any progress on this issue?

**Comment by dastcaboz** [comment]
In both, life version and test version, it still just the farmer name as owner, not the famer code or a combinatiuon of bioth. This is not secure!

<img width="1440" alt="life_version_vendor_location-farmer" src="https://user-images.githubusercontent.com/90847414/137481454-33fd1761-f3dd-4156-924a-a964ea8eafe2.png">

**Comment by treviser** [comment]
@dastcaboz As we were able to update the code meanwhile, please check.
