### ISSUE TITLE
History (owner/farmer) of a plantation cannot get deleted

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#22]
<img width="1792" alt="Bildschirmfoto 2021-09-17 um 09 42 37" src="https://user-images.githubusercontent.com/90847414/133744759-a43b69e9-1097-40c6-91db-a39febeeadd3.png">

**Comment by treviser** [comment]
This is by design

The association between farmer and plantation is managed at the farmer side. The history at the plantation side is only for information purposes.

![image](https://user-images.githubusercontent.com/1814941/133749955-5429347e-806f-4f58-ace8-817c38d6939f.png)

If you consider it as important, then this must be marked as enhancement request.

**Comment by dastcaboz** [comment]
Makes sense. In this case we can close this issue and refer it to issue #23
