### ISSUE TITLE
Reduced farmer creation form

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#25]
Farmer creation form has too many fields we do not need. Unnecessary fields can generate data errors.

Question 1) Is it possible to adapt the fields depending on the type of contact? Individial, Company, Farmer? Some fields might be useful for a company, but not for a farmer.

Question 2) The Tick-box _Is Farmer?_ is maybe better placed at the top of the form next to _Particulier_ and _Company_

<img width="1594" alt="Bildschirmfoto 2021-09-17 um 16 18 22" src="https://user-images.githubusercontent.com/90847414/133799758-d03a5f1b-fdd4-4321-ad40-7062827fad3b.png">
_?

**Comment by treviser** [comment]
@dastcaboz I'm not sure if this is really helpful. We should not remove the address, we should also not remove the tab "Contacts & Adresses", as it may be of future use and it is not in the way. The only fields which might be obsolote are
- TVA
- Poste Occupé
- Site Web

In my opinion the benefit is by far not worth the effort of changing a default partner form for a particular partner role only. Besides that, it is not possible to change the form before knowing the role of a partner to be entered.
Also I do not recommend to move the partner role up to the side of partner type (person / company), because the role is not related to the partner type, this might lead to confusion, especially if future roles would be implemented. It would induce the meaning that it is an exclusive selection (a partner could be either an individual, a company or a farmer), which is not true.

I suggest to close this issue with no further action.

**Comment by treviser** [comment]
As an additional remark: the fact that a partner form looks the same throughout the system no matter what kind of partner has a benefit and value by itself for the user.

**Comment by dastcaboz** [comment]
Then lets leave it as it is.
