### ISSUE TITLE
Limit choice of partners when creating a purchase order

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#27]
<img width="1440" alt="Bildschirmfoto 2021-09-22 um 19 14 14" src="https://user-images.githubusercontent.com/90847414/134390613-16346d1c-b6ed-4aef-9d43-a12e7057b90d.png">
Limit the selection in the dropbdown to pisteurs (cocoa buyers) or exclude all farmers from this list.
For your attention: A pisteur can be at the same time a farmer and sell his own production. Do we have to register in this case the same person in its two roles?

<img width="1440" alt="Bildschirmfoto 2021-09-22 um 19 21 38" src="https://user-images.githubusercontent.com/90847414/134391671-62d6db2c-209d-4845-94ef-6b149122efed.png">
The same issue with vendor payments. Exclude all farmers from this list.

**Comment by treviser** [comment]
@dastcaboz  For the common understanding please use the english term "purchasing agent" for "Pisteur", as we did so until now.

**Comment by treviser** [comment]
@dastcaboz Introducing the possibility to assign also the role of a purchasing agent to a farmer seriously breaks our current core design and the traceability. Core property of a farmer is that he has a dedicated vendor location automatically assigned in order to trace his deliveries in lots. On the other hand creating different partners for the same real person is a design flaw and leads to inevitable inconsistencies. We have to carefully analyse this new requirement and eventually take a decision.

As a first step I suggest that we exclude farmers from the selection dropdown in requests for quotation and purchase orders.

**Comment by dastcaboz** [comment]
Agreed for the first step. 

As for the double role of the purchaising agents as a farmer: Yes this would be a design flaw. But as we do not talk about many persons (about 30 purchaising agents in relation to 1550 farmers) I think we can handle this pragmatically for the moment by creating for the same person the to roles. But if there is a way to handle this in within the logic framework even the better.
