### ISSUE TITLE
Internal Pick Move is generated automatically after Stock Move from Vendor Location to Stock

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#32]
Pick move from Stock to Output should be a purely manual operation.
<img width="1089" alt="Bildschirmfoto 2021-09-24 um 11 50 12" src="https://user-images.githubusercontent.com/90847414/134655587-466bc3ab-528d-48ed-8d36-01f7eadfabd6.png">

**Comment by treviser** [comment]
@candidroot Please see my skype message to Siddharth, this is very urgent. I can not understand this behaviour, it might be a setup issue, but I'm not aware of where exactly.

**Comment by treviser** [comment]
@candidroot Any news on this?

**Comment by candidroot** [comment]
@treviser 
can you please check on test server i already change rule for that.
Please let me know is it working fine or not ??

**Comment by treviser** [comment]
@candidroot 
I just broke my notebook and have to fix it. As you have admin access to the test database, could you please test the last changes you have made and provide the screenshots in the related issues? Also please tell me which change you have made to which rule concerning the issue here?

I thank you very much for your support.

**Comment by candidroot** [comment]
@treviser 
Please have look this screenshot in that i have mentioned what i have changes
![screenshot-test-caboz twanda-hosting ch-2021 10 05-15_09_10](https://user-images.githubusercontent.com/39722234/135999549-8cde9f7c-ed30-432f-b52a-1f86fcf7f6f6.png)
.

**Comment by dastcaboz** [comment]
This issue is in my opinion resolved.
