### ISSUE TITLE
Redefine Plantation datamodel

### ISSUE THREAD

**Issue by dastcaboz** [twanda/vertical-agriculture#63]
@ Siddharth: As discussed plaese find a scetch how the new datamodel for plantation should look like:
[Odoo Datenbank Plantation .pdf](https://github.com/twanda/vertical-agriculture/files/8117952/Odoo.Datenbank.Plantation.pdf)

A **person (partner)** is the legal owner of one to several plantations and
owns or exploits one or several plots. The owner of a plantation can be
different from the person who exploits the plots belongig to the
plantation.
2. A **plantation** consists of one to several plots. All plots are
geographically attached to one another.
3. Each **plot** belongs to one plantation and is exploited by one farmer,
but a farmer can exploit several plots. Each plot has one type and
geographical informations such as a centerpoint and a GPS polygons.

**Comment by zemade** [comment]
Hi Siddharth

I am Zeno, the brother of Ermin. As Ermin is still not doing well, I am taking over to support Caboz in going forward with their project. In respect to the above requirement to re-structure the plantation and introduction of plots I have have worked out a specification which is attached to this comment. The objective is, that you can implement the new objects accordingly. As a first step, can you please read through the specification and raise any questions or comments you may have so that we can generate a common understanding before starting implementation?

Looking forward to hearing from you soon.

Cheers
Zeno
[Specification_Farms_v1_0.pdf](https://github.com/twanda/vertical-agriculture/files/8799465/Specification_Farms_v1_0.pdf)

**Comment by siddharth7815** [comment]
@dastcaboz issue has been resolved. please have a look.

**Comment by dastcaboz** [comment]
@siddharth7815 We should look at this in a call.
